import type { FrameworkAdapter, SourceContext } from "@awe/adapters";
import type { RemediationInstruction } from "@awe/core";
import type { GateOptions } from "@awe/sandbox";
import { runBuildGate } from "@awe/sandbox";
import type { RepoRef, VcsProvider } from "./provider";

export interface RepoPrDeps {
  adapter: FrameworkAdapter;
  vcs: VcsProvider;
  /** Runs the sandbox build gate; injected for testing. */
  gate?: typeof runBuildGate;
  build?: GateOptions["build"];
}

export interface RepoPrInput {
  instruction: RemediationInstruction;
  repo: RepoRef;
  repoRoot: string;
  route: string;
  /** Issue types already present, so the gate only fails on NEW ones. */
  baseline?: Set<RemediationInstruction["finding"]["issueType"]>;
}

/** Why the source rail declined; the caller serves the universal Patch rail. */
export type FallbackReason =
  | "unmappable"
  | "adapter_declined"
  | "build_failed"
  | "not_resolved"
  | "new_issue"
  | "no_verifiable_output";

export type RepoPrOutcome =
  | { status: "opened"; url: string; number: number; branch: string }
  | { status: "fallback"; reason: FallbackReason };

/**
 * Policy 3 — the Repo PR rail.
 *
 * Composes the three Phase-3 pieces into one flow and enforces the central
 * safety rule at every step: **when the source rail cannot produce a verified
 * fix, it declines rather than degrading quality.** Every decline returns a
 * `fallback` outcome so the caller can serve the universal Patch rail instead —
 * so a connected repo is never *worse* off than an unconnected one.
 *
 *   map route → adapter.applyToSource → build gate → open PR
 *      ↓ none        ↓ null              ↓ !passed
 *   fallback       fallback            fallback
 */
export async function openRepoPr(input: RepoPrInput, deps: RepoPrDeps): Promise<RepoPrOutcome> {
  const gate = deps.gate ?? runBuildGate;
  const { instruction } = input;

  const files = await deps.adapter.mapRoute(input.route, input.repoRoot);
  if (files.length === 0) return { status: "fallback", reason: "unmappable" };

  const ctx: SourceContext = { repoRoot: input.repoRoot, route: input.route, files };
  const patch = await deps.adapter.applyToSource(instruction, ctx);
  if (!patch) return { status: "fallback", reason: "adapter_declined" };

  const verdict = await gate(patch, {
    issueType: instruction.finding.issueType,
    url: instruction.finding.url,
    ...(input.baseline ? { baseline: input.baseline } : {}),
    ...(deps.build ? { build: deps.build } : {}),
  });
  if (!verdict.passed) return { status: "fallback", reason: verdict.reason };

  const branch = branchName(instruction);
  const pr = await deps.vcs.openPullRequest({
    repo: input.repo,
    branch,
    title: prTitle(instruction),
    body: prBody(instruction, patch.framework),
    patch,
  });
  return { status: "opened", url: pr.url, number: pr.number, branch: pr.branch };
}

function branchName(instruction: RemediationInstruction): string {
  const slug = instruction.finding.issueType.replace(/_/g, "-");
  const route = instruction.finding.route ?? instruction.finding.url;
  const hash = Math.abs(hashString(route)).toString(36).slice(0, 6);
  return `awe/${slug}-${hash}`;
}

function prTitle(instruction: RemediationInstruction): string {
  return `fix(seo): ${instruction.finding.issueType.replace(/_/g, " ")} on ${routeLabel(instruction)}`;
}

function prBody(instruction: RemediationInstruction, framework: string): string {
  const pct = Math.round(instruction.confidence * 100);
  return [
    `**Issue:** ${instruction.finding.issueType}`,
    `**What's wrong:** ${instruction.whatIsWrong}`,
    `**Why it matters:** ${instruction.whyItMatters}`,
    `**Impact:** ${instruction.expectedImpact} · **Confidence:** ${pct}%`,
    "",
    `Generated by AI Website Engineer (${framework} adapter). Validated by the build gate: the change builds and resolves the issue without introducing new ones.`,
    "",
    "🤖 Review and merge, or edit as needed.",
  ].join("\n");
}

function routeLabel(instruction: RemediationInstruction): string {
  return instruction.finding.route ?? instruction.finding.url;
}

function hashString(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i++) {
    hash = (hash << 5) - hash + value.charCodeAt(i);
    hash |= 0;
  }
  return hash;
}
